//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mieszkania
{
    using System;
    using System.Collections.Generic;
    
    public partial class Czynsz_Wplywy
    {
        public int IdCzynszu { get; set; }
        public int IdUmowy { get; set; }
        public decimal Kwota { get; set; }
        public System.DateTime Termin_Rozliczenia { get; set; }
        public Nullable<bool> Zaplacone { get; set; }
    
        public virtual Umowa Umowa { get; set; }
    }
}
