//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mieszkania
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    
    public partial class DostepPrac : DbContext
    {
        public DostepPrac()
            : base("name=DostepPrac")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<Autoryzacja> Autoryzacja { get; set; }
        public virtual DbSet<Czynsz_Wplywy> Czynsz_Wplywy { get; set; }
        public virtual DbSet<Lokator> Lokator { get; set; }
        public virtual DbSet<Mieszkanie> Mieszkanie { get; set; }
        public virtual DbSet<Pracownicy> Pracownicy { get; set; }
        public virtual DbSet<Pracownicy_Odp> Pracownicy_Odp { get; set; }
        public virtual DbSet<Remonty> Remonty { get; set; }
        public virtual DbSet<Stanowiska> Stanowiska { get; set; }
        public virtual DbSet<Umowa> Umowa { get; set; }
    }
}
