//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mieszkania
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pracownicy_Odp
    {
        public int IdPracownika { get; set; }
        public int IdMieszkania { get; set; }
        public int IdOperacji { get; set; }
    }
}
