//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mieszkania
{
    using System;
    using System.Collections.Generic;
    
    public partial class Remonty
    {
        public int IdRemontu { get; set; }
        public int IdMieszkania { get; set; }
        public string Stan { get; set; }
        public decimal Koszt_Remontu { get; set; }
        public System.DateTime Data_Rozpoczecia { get; set; }
        public Nullable<System.DateTime> Data_Zakonczenia { get; set; }
    
        public virtual Mieszkanie Mieszkanie { get; set; }
    }
}
