//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mieszkania
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowa
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Umowa()
        {
            this.Czynsz_Wplywy = new HashSet<Czynsz_Wplywy>();
        }
    
        public int IdUmowy { get; set; }
        public int IdMieszkania { get; set; }
        public int IdLokatora { get; set; }
        public System.DateTime Od_Kiedy { get; set; }
        public Nullable<System.DateTime> Do_Kiedy { get; set; }
        public decimal Stawka_Czynsz { get; set; }
        public decimal Oplaty_Stale { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Czynsz_Wplywy> Czynsz_Wplywy { get; set; }
        public virtual Lokator Lokator { get; set; }
        public virtual Mieszkanie Mieszkanie { get; set; }
    }
}
