//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Mieszkania
{
    using System;
    using System.Collections.Generic;
    
    public partial class Umowa
    {
        public int IdUmowy { get; set; }
        public int IdMieszkania { get; set; }
        public int IdLokatora { get; set; }
        public System.DateTime Od_Kiedy { get; set; }
        public Nullable<System.DateTime> Do_Kiedy { get; set; }
        public Nullable<System.DateTime> Termin_Rozliczenia { get; set; }
        public decimal Czynsz { get; set; }
        public decimal Oplaty_Stale { get; set; }
    }
}
